version: "3.8"

services:
  kafka-1:
    image: apache/kafka:4.1.1
    ports:
      - "9092:9092"
      - "9091:9091"
    environment:
      KAFKA_KRAFT_MODE: "true"
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-1:9091"
      KAFKA_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9091"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_LOG_DIRS: "/kafka-logs"
    volumes:
      - ./volumes/server-1:/kafka-logs
